//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public int Numara { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<decimal> Telefon { get; set; }
        public Nullable<int> BolumID { get; set; }
        public Nullable<int> FakulteID { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Fakulteler Fakulteler { get; set; }
    }
}
